CFLAGS= -std=gnu++98 -pedantic -Wall -Werror -ggdb3

all:cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4

cyoa-step1: cyoa-step1.cpp page.cpp page.h
	g++ $(CFLAGS) -o cyoa-step1 cyoa-step1.cpp page.cpp

cyoa-step2: cyoa-step2.cpp page.cpp page.h
	g++ $(CFLAGS) -o cyoa-step2 cyoa-step2.cpp page.cpp

cyoa-step3: cyoa-step3.cpp page.cpp page.h
	g++ $(CFLAGS) -o cyoa-step3 cyoa-step3.cpp page.cpp

cyoa-step4: cyoa-step4.cpp page.cpp page.h
	g++ $(CFLAGS) -o cyoa-step4 cyoa-step4.cpp page.cpp
